blog/urls.py
from django.urls import path
from blog.views import PostDetailView, UploadPostView, PostUpdateView, PostLikeView

app_name = "blog"

urlpatterns = [
    path("upload-file/", UploadPostView.as_view(), name="post_file_upload"),
    path("like/", PostLikeView.as_view(), name="post_like_view"),
    path("<slug:post_slug>/", PostDetailView.as_view(), name="post_detail_view"),
]

blog_news/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include
from blog.views import PostListView, post_creat_view, PostUpdateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls", namespace="blog")),
    path("login/", include("login.urls", namespace="login")),
    path("", PostListView.as_view(), name="post_list_view"),
    path("create/", post_creat_view, name="post_create_view"),
    path("update/<slug:post_slug>", PostUpdateView.as_view(), name="post_update_view"),
    path("<parameter>/", PostListView.as_view(), name="post_list_view_sort"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from login.views import (
    LoginView,
    LogoutView,
    RegistrationView,
    edit,
    FavoriteView,
    FavoriteListView,
)

app_name = "login"

urlpatterns = [
    path("", LoginView.as_view(), name="login_view"),
    path("logout/", LogoutView.as_view(), name="logout_view"),
    path("registration/", RegistrationView.as_view(), name="registration_view"),
    path("edit/", edit, name="edit_view"),
    path("favorites/<int:id>", FavoriteView.as_view(), name="favorites_add"),
    path("favorites-list/", FavoriteListView.as_view(), name="favorites_list_view"),
]

login/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.db import models
from django.contrib.auth.models import User


class Profile(AbstractBaseUser):
    profile_username = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_description = models.TextField(blank=True, null=True)
    profile_photo = models.ImageField(default="img/standart_avatar.png")

    USERNAME_FIELD = "profile_username"

    def __str__(self):
        return f"Профиль пользователя {self.profile_username}"

login/forms.py
from django import forms
from django.contrib.auth.forms import (
    UserCreationForm,
    AuthenticationForm,
    UsernameField,
)
from login.models import Profile, User


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class RegisterForm(UserCreationForm):
    profile_first_name = forms.CharField(required=False)
    profile_last_name = forms.CharField(required=False)
    profile_description = forms.Textarea()
    profile_photo = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = ["username", "password1", "password2"]


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name"]


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["profile_description", "profile_photo"]

login/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.views import LoginView, LogoutView, FormView
from django.views.generic import ListView

from .forms import CustomAuthenticationForm, RegisterForm, UserEditForm, ProfileEditForm
from login.models import Profile, User

from blog.models import Post


class LoginView(LoginView):
    template_name = "login/login.html"
    form_class = CustomAuthenticationForm


class RegistrationView(FormView):
    template_name = "login/registration.html"
    form_class = RegisterForm

    def form_valid(self, form):
        new_user = form.save()
        profile_username = form.cleaned_data.get("username")
        user = User.objects.get(username=profile_username)
        user.first_name = form.cleaned_data.get("profile_first_name")
        user.last_name = form.cleaned_data.get("profile_last_name")

        user.save()
        Profile.objects.create(
            profile_username=new_user,
            profile_description=form.cleaned_data.get("profile_description"),
        )

        login(self.request, user)
        return redirect("/")


@login_required
def edit(request):
    if request.method == "POST":
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user, data=request.POST)
        if request.FILES.get("profile_photo"):
            request.user.profile.profile_photo = request.FILES["profile_photo"]
            request.user.profile.save()
        if user_form.is_valid() and profile_form.is_valid():
            request.user.profile.profile_description = request.POST[
                "profile_description"
            ]
            request.user.profile.save()
            profile_form.save()
            user_form.save()
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(
        request,
        "login/edit.html",
        context={"user_form": user_form, "profile_form": profile_form},
    )


class FavoriteView(LoginRequiredMixin, View):
    def get(self, request, id):
        post = self.get_object(id)
        if post.post_user_favorite.filter(id=self.request.user.id).exists():
            post.post_user_favorite.remove(self.request.user)
        else:
            print(post.post_user_favorite.add(request.user))
        return HttpResponseRedirect(self.request.META["HTTP_REFERER"])

    def get_object(self, id):
        return get_object_or_404(Post, id=id)


class FavoriteListView(LoginRequiredMixin, ListView):
    template_name = "login/favorites-list.html"

    def get_queryset(self):
        return Post.post_objects.filter(post_user_favorite=self.request.user)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(FavoriteListView, self).get_context_data(**kwargs)
        context["posts"] = self.get_queryset()
        return context

login/templates/login/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %} Главная страница новостного сайта {% endblock %}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-ligth bg-dark">
  <div class="container">
    <a class="navbar-brand white" href="{% url 'post_list_view' %}">Blog</a>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a href="{% url 'post_create_view' %}" class="nav-link">
          Создать блог
        </a>
      </div>
      <div class="navbar-nav">
        <a href="{% url 'blog:post_file_upload' %}" class="nav-link">
          Загрузить несколько блогов
        </a>
      </div>
      <div class="navbar-nav">
        <a href="{% url 'login:favorites_list_view' %}" class="nav-link">
          Избранные записи
        </a>
      </div>
    </div>
    <ul class="navbar-nav">
      {% if not user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'login:login_view' %}" class="nav-link">
            Авторизация
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'login:registration_view' %}" class="nav-link">
            Регистрация
          </a>
        </li>
      {% else %}
        <li class="nav-item">
          <a href="{% url 'login:edit_view' %}" class="nav-link ">
            <img src="{{ user.profile.profile_photo.url }}" alt="{{ user.username }}"
                 class="rounded-circle" style="height: 30px">
            {{ user.username }}
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'login:logout_view' %}" class="nav-link text-secondary">
            Выйти
          </a>
        </li>
      {% endif %}
    </ul>
  </div>

</nav>
<div class="container">
  {% block content %}{% endblock %}
</div>
</body>
</html>

login/templates/login/edit.html
{% extends "login/base.html" %}
{% block title %}Редактирование профиля{% endblock %}
{% block content %}
<h1>Редактирование профиля</h1>
<form action="." method="post" enctype="multipart/form-data">
    {% csrf_token %}
  {{ user_form.as_p }}
  {{ profile_form.as_p }}
  <input type="submit" value="Сохранить изменения">
</form>
{% endblock %}

login/templates/login/favorites-list.html
{% extends "login/base.html" %}
{% block title %}Избранные новости{% endblock %}
{% block content %}
  <section class="row">
  <h2>Избранные записи</h2>
    <div class="container">
      {% for post in posts %}
        <div class="col-lg-6 mb-5">
          <div class="card" {% if post.post_image %}
               style="background-image: url('{{ post.post_image.url }}')" {% endif %}>
            <div class="card-body">
              <h3 class="card-title">{{ post.post_title }}</h3>
              <p class="card-text">{{ post.post_short_description|truncatechars:9 }}</p>
              <p>{{ post_created }}</p>
              <ul class="list-group list-group-flush mb-3">
                <li class="list-group-item">Опубликовано: {{ post.post_created }}</li>
                <li class="list-group-item">Отредактировано: {{ post.post_updated }}</li>
                <li class="list-group-item">Рейтинг: {{ post.post_rating }}</li>
                <li class="list-group-item">Количество просмотров: {{ post.post_count_view }}</li>
              </ul>
              <a href="{{ post.get_absolute_url }}" class="btn btn-primary float-right stretched-link">К новости</a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </section>
{% endblock %}

login/templates/login/login.html
{% extends 'login/base.html' %}
{% block title %}Авторизация{% endblock %}
{% block content %}
<h1>Авторизация</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button class="btn btn-primary" type="submit">Login</button>
</form>
{% endblock %}

login/templates/login/registration.html
{% extends 'login/base.html' %}
{% block title %}Регистрация{% endblock %}
{% block content %}
<h2 class="">Регистрация</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Зарегистрироваться</button>
  </form>
{% endblock %}