blog/urls.py
from django.urls import path
from blog.views import PostDetailView, UploadPostView, PostUpdateView, PostLikeView

app_name = "blog"

urlpatterns = [
    path("upload-file/", UploadPostView.as_view(), name="post_file_upload"),
    path("like/", PostLikeView.as_view(), name="post_like_view"),
    path("<slug:post_slug>/", PostDetailView.as_view(), name="post_detail_view"),
]

blog_news/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include
from blog.views import PostListView, post_creat_view, PostUpdateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls", namespace="blog")),
    path("login/", include("login.urls", namespace="login")),
    path("", PostListView.as_view(), name="post_list_view"),
    path("create/", post_creat_view, name="post_create_view"),
    path("update/<slug:post_slug>", PostUpdateView.as_view(), name="post_update_view"),
    path("<parameter>/", PostListView.as_view(), name="post_list_view_sort"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from login.views import (
    LoginView,
    LogoutView,
    RegistrationView,
    edit,
    FavoriteView,
    FavoriteListView,
)

app_name = "login"

urlpatterns = [
    path("", LoginView.as_view(), name="login_view"),
    path("logout/", LogoutView.as_view(), name="logout_view"),
    path("registration/", RegistrationView.as_view(), name="registration_view"),
    path("edit/", edit, name="edit_view"),
    path("favorites/<int:id>", FavoriteView.as_view(), name="favorites_add"),
    path("favorites-list/", FavoriteListView.as_view(), name="favorites_list_view"),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):

    post_barcode = models.IntegerField(unique=True, default=0)
    post_title = models.CharField(max_length=250)
    post_author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    post_short_description = models.CharField(
        max_length=250, verbose_name="Краткое описание", default="Краткое описание"
    )
    post_text = models.TextField(verbose_name="Полное описание")
    post_created = models.DateTimeField(auto_now_add=True)
    post_updated = models.DateTimeField(auto_now=True)
    post_slug = models.SlugField()
    post_objects = models.Manager()
    post_rating = models.IntegerField(default=0)
    post_count_view = models.IntegerField(default=0)
    post_user_like = models.ManyToManyField(
        User, related_name="post_liked", default=None, blank=True
    )
    post_user_dislike = models.ManyToManyField(
        User, related_name="post_disliked", default=None, blank=True
    )
    post_user_favorite = models.ManyToManyField(
        User, related_name="favorite", default=None, blank=True
    )

    class Meta:
        ordering = ["-post_created"]

    def __str__(self):
        return self.post_title

    def get_absolute_url(self):
        return reverse("blog:post_detail_view", args=[self.post_slug])


class Images(models.Model):
    image = models.FileField(upload_to="static/img/", blank=True, null=True)
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="images", blank=True, null=True
    )
    objects = models.Manager()

blog/forms.py
from django import forms
from blog.models import Post, Images


class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["post_title", "post_barcode", "post_text"]


class CreateImageForm(forms.ModelForm):
    class Meta:
        model = Images
        fields = ["image"]
        widgets = {
            "image": forms.ClearableFileInput(
                attrs={
                    "multiple": True,
                    "enctype": "multipart/form-data",
                }
            )
        }


class UploadPostForm(forms.Form):
    file = forms.FileField()

blog/views.py
import csv

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, DetailView, FormView, UpdateView, View
from blog.forms import UploadPostForm, CreateImageForm, CreatePostForm
from django.http import HttpResponseRedirect

from uuslug import slugify

from blog.models import Post, Images


class PostListView(ListView):
    """
    Отображение списка постов
    """

    paginate_by = 5
    model = Post
    context_object_name = "posts"
    template_name = "blog/list.html"

    def get_context_data(self, object_list=None, **kwargs):
        context = super(PostListView, self).get_context_data(
            object_list=object_list, **kwargs
        )
        context["page"] = self.paginate_by

        if self.kwargs.get("parameter"):
            context["posts"] = self.get_queryset(self.kwargs.get("parameter"))
        return context

    def get(self, request, **kwargs):
        if self.request.GET.get("count_post"):
            self.paginate_by = int(self.request.GET.get("count_post"))
        return super(PostListView, self).get(request, **kwargs)

    def get_queryset(self, parameter="-post_created"):
        return Post.post_objects.order_by(str(parameter))


class PostDetailView(DetailView):
    """
    Детальное отображение постов
    """

    model = Post
    template_name = "blog/detail.html"
    context_object_name = "post"

    def get(self, request, *args, **kwargs):
        object = self.get_object()
        object.post_count_view += 1
        object.save()
        return super(PostDetailView, self).get(request, *args, **kwargs)

    def get_object(self, queryset=None):
        return Post.post_objects.get(post_slug=self.kwargs["post_slug"])

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context["images"] = self.object.images.all()
        return context


@login_required(login_url="/login")
def post_creat_view(request):
    if request.POST:
        post_form = CreatePostForm(data=request.POST)
        image_form = CreateImageForm(data=request.POST, files=request.FILES)

        if post_form.is_valid() and image_form.is_valid():
            post_form.instance.post_author = request.user
            post_form.instance.post_slug = slugify(
                post_form.cleaned_data.get("post_title")
            )

            image_form.instance.post = post_form.instance
            images = request.FILES.getlist("image")
            post_form.save()
            for image in images:
                _ = Images(image=image, post=post_form.instance).save()

            return redirect("/")
    else:
        post_form = CreatePostForm()
        image_form = CreateImageForm()
    return render(
        request,
        "blog/create.html",
        context={"post_form": post_form, "image_form": image_form},
    )


class UploadPostView(LoginRequiredMixin, FormView):
    """
    Загрузка нескольких блогов через csv файл
    """

    template_name = "blog/upload_file.html"
    form_class = UploadPostForm
    login_url = "/login/"

    def form_valid(self, form):
        file = form.cleaned_data.get("file").read()
        post_text = file.decode("utf-8").split("\n")
        csv_reader = csv.reader(post_text, delimiter=";", quotechar='"')
        for row in csv_reader:
            Post.post_objects.create(
                post_slug=slugify(row[0]),
                post_title=row[0],
                post_author=self.request.user,
                post_text=row[1],
                post_barcode=row[2],
            )
        return super(UploadPostView, self).form_valid(form)

    def get_success_url(self):
        return reverse("post_list_view")


class PostUpdateView(LoginRequiredMixin, UpdateView):
    """
    Изменение записи
    """

    model = Post
    template_name = "blog/post_update.html"
    fields = ["post_title", "post_text", "post_slug", "post_short_description"]

    def get_object(self, queryset=None):
        return get_object_or_404(Post, post_slug=self.kwargs.get("post_slug"))

    def form_valid(self, form):
        return super(PostUpdateView, self).form_valid(form)

    def test_func(self):
        """
        Проверка, что пользователь это автор и
        позволяет ему редактировать пост иначе 403
        """
        obj = self.get_object()
        return obj.post_author == self.request.user


class PostLikeView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        """
        Подсчет 'лайков' и 'дизлайков'
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        post_id = self.request.POST.get("dislike") or self.request.POST.get("like")
        post = Post.post_objects.get(id=post_id)
        if self.request.user in post.post_user_like.filter(username=self.request.user):
            if self.request.POST.get("like"):
                post.post_user_like.remove(self.request.user)
                post.post_rating -= 1
            elif self.request.POST.get("dislike"):
                post.post_user_like.remove(self.request.user)
                post.post_user_dislike.add(self.request.user)
                post.post_rating -= 2
        elif self.request.user in post.post_user_dislike.filter(
            username=self.request.user
        ):
            if self.request.POST.get("dislike"):
                post.post_rating += 1
                post.post_user_dislike.remove(self.request.user)

            elif self.request.POST.get("like"):
                post.post_user_like.add(self.request.user)
                post.post_user_dislike.remove(self.request.user)
                post.post_rating += 2
        else:
            if self.request.POST.get("like"):
                post.post_rating += 1
                post.post_user_like.add(self.request.user)

            else:
                post.post_rating -= 1
                post.post_user_dislike.add(self.request.user)
        post.save()

        return HttpResponseRedirect(
            reverse("blog:post_detail_view", args=[post.post_slug])
        )

blog/templates/blog/create.html
{% extends 'login/base.html' %}
{% block title %}Создание блога{% endblock %}
{% block content %}
<h1>Создание новости</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ post_form.as_p }}
    {{ image_form.as_p }}
     <input type="submit">
</form>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'login/base.html' %}
{% block title %} {{ post.post_title }} {% endblock %}
{% block content %}
  <h1>{{ post.post_title }}</h1>

  <div class="row">
    <div class="col-sm-8">
      <h5>{{ post.post_created }}</h5>
      <a class="btn btn-primary" href="{% url 'login:favorites_add' post.id %}">
        Добавить в избранное
      </a>
    {% if post.post_author == request.user %}
      <a class="btn btn-danger" href="{% url 'post_update_view' post.post_slug %}">
        Редактировать
      </a>
    {% endif %}
      <p class="lead">{{ post.post_text }}</p>
      {% for image in post.images.all %}
        <img src="{{ image.image.url }}" alt="{{ post.post_title }}">
      {% endfor %}
    </div>
  </div>

  <p>
    Рейтинг статьи: {{ post.post_rating }}
  </p>
  <form action="{% url 'blog:post_like_view' %}" method="post">
  {% csrf_token %}
  <button class="btn btn-primary " type="submit" name="like" value="{{ post.id }}">Нравится!</button>
  <button class="btn btn-danger" type="submit" name="dislike" value="{{ post.id }}">Не нравится!</button>

  </form>
{% endblock %}

blog/templates/blog/list.html
{% extends 'login/base.html' %}
{% load static %}
{% block content %}
  <h1>Блог</h1>
  <div class="row">
    <p>Сортировать по:</p>
    <ul>
      <li>
        <a href="{% url 'post_list_view_sort' 'post_created' %}">Дате</a>
      </li>
      <li>
        <a href="{% url 'post_list_view_sort' '-post_rating' %}">Рейтинг убывающий</a>
      </li>
      <li>
        <a href="{% url 'post_list_view_sort' 'post_rating' %}">рейтинг Возрастаешь</a>
      </li>
    </ul>
    <form action="." method="get">
      <label for="count_post">Количество записей на странице</label>
      <select name="count_post" id="">
        <option value="2">2</option>
        <option value="5">5</option>
        <option value="10">10</option>
        <option value="15">15</option>
      </select>
      <button type="submit">Подтвердить</button>
    </form>

  </div>
  <div class="row">
    {% for post in posts %}
      <div class="col-lg-6 mb-5">
        <div class="card" {% if post.post_image %}
             style="background-image: url('{{ post.post_image.url }}')" {% endif %}>
          <div class="card-body">
            <h3 class="card-title">{{ post.post_title }}</h3>
            <p class="card-text">{{ post.post_short_description|truncatechars:9 }}</p>
            <p>{{ post_created }}</p>
            <ul class="list-group list-group-flush mb-3">
              <li class="list-group-item">Опубликовано: {{ post.post_created }}</li>
              <li class="list-group-item">Отредактировано: {{ post.post_updated }}</li>
              <li class="list-group-item">Рейтинг: {{ post.post_rating }}</li>
              <li class="list-group-item">Количество просмотров: {{ post.post_count_view }}</li>
            </ul>
            <a href="{{ post.get_absolute_url }}" class="btn btn-primary float-right stretched-link">К новости</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; Первая</a>
            <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        {% endif %}

        <span class="current">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}

blog/templates/blog/post_update.html
{% extends 'login/base.html' %}
{% block title %} Редактирование новости {% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>
{% endblock %}

blog/templates/blog/upload_file.html
{% extends 'login/base.html' %}
{% block title %} Загрузка постов файлом {% endblock %}
{% block content %}
<h1>Загрузка файла с постами</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Загрузить файл</button>
</form>
{% endblock %}